services:
  ms-usuarios:
    build: ./ms-clientes
    container_name: ms-clientes
    ports:
      - "8083:8083"

  ms-catalogo:
    build: ./wepay-catalogo
    container_name: ms-catalogo
    ports:
      - "8084:8084"

  ms-pedidos:
    build: ./ms-pedidos
    container_name: ms-pedidos
    ports:
      - "8085:8085"

  api-bff:
    build: ./api
    container_name: api-bff
    ports:
      - "8081:8081"
    environment:
      - ENTRA_ISSUER_URI=${ENTRA_ISSUER_URI}
      - ENTRA_API_CLIENT_ID=${ENTRA_API_CLIENT_ID}
      - MS_USUARIOS_URL=http://ms-usuarios:8083
      - MS_PRODUCTOS_URL=http://ms-catalogo:8084
      - MS_PEDIDOS_URL=http://ms-pedidos:8085
    depends_on:
      - ms-usuarios
      - ms-catalogo
      - ms-pedidos